server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://192.168.205.4:3306/moemall
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml