version: '3.1'

services: 
  mysql:
    image: mysql:8.0.17
    container_name: moemall-mysql
    restart: always
    ports: 
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - my-bridge
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: moemall
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
  redis:
    image: redis:5.0.6-alpine
    container_name: moemall-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    networks:
      - my-bridge


networks: 
  my-bridge: 
    driver: bridge
